version: '3'

services:
  development-server:
    container_name: "wed-development-server"
    build:
      dockerfile: Dockerfile.development
      context: .
    restart: on-failure
    volumes:
      - ./wed:/home/node/wed
      - ./www:/home/node/vhosts/public
    ports:
      - 8088:80
