#!/usr/bin/env sh

case "${COMMON}" in
"1")
  docker build -f Dockerfile.common -t "${IMAGE_NAME}" .
  ;;
*)
  COMMON_VERSION=latest
  docker pull iordaniskostelidis/wed-ds-common:"${COMMON_VERSION}" \
     && docker tag iordaniskostelidis/wed-ds-common:"${COMMON_VERSION}" wed-ds-common:latest \
     && docker build -f Dockerfile.production -t "${IMAGE_NAME}" .
  ;;
esac
